export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';
export const INVALID_OTP = 'INVALID_OTP';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const USER_NOT_FOUND_WITH_THIS_MOBILE_NUMBER =
  'USER_NOT_FOUND_WITH_THIS_MOBILE_NUMBER';
export const USER_ALREADY_EXISTS_WITH_THIS_MOBILE_NUMBER =
  'USER_ALREADY_EXISTS_WITH_THIS_MOBILE_NUMBER';
export const USER_ALREADY_EXISTS_WITH_THIS_EMAIL =
  'USER_ALREADY_EXISTS_WITH_THIS_EMAIL';
export const USER_MOBILE_NUMBER_IS_NOT_VERIFIED =
  'USER_MOBILE_NUMBER_IS_NOT_VERIFIED';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const INVALID_RESET_PASSWORD_TOKEN = 'INVALID_RESET_PASSWORD_TOKEN';
export const RESET_PASSWORD_TOKEN_EXPIRED = 'RESET_PASSWORD_TOKEN_EXPIRED';
export const INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE';
